// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    noPreviewFeatureMessage: string;
}
declare var cssExports: CssExports;
export = cssExports;
