// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
export enum StoreNames {
    VisualizationStore,
    TabStore,
    VisualizationScanResultStore,
    CommandStore,
    FeatureFlagStore,
    LaunchPanelStateStore,
    DevToolsStore,
    DetailsViewStore,
    AssessmentStore,
    ScopingPanelStateStore,
    InspectStore,
    UserConfigurationStore,
    PathSnippetStore,
    UnifiedScanResultStore,
    CardSelectionStore,
    DeviceStore,
    WindowStateStore,
    ScanStore,
    PermissionsStateStore,
    DebugToolsNavStore,
    AndroidSetupStore,
    LeftNavStore,
    ContentPanelStore,
    DeviceConnectionStore,
    TabStopsStore,
}
