# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# This prevents inconsistent timeouts during yarn install of the large office fabric fonts package
# See https://github.com/yarnpkg/yarn/issues/5540#issuecomment-374069461
httpTimeout: 120000

nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.5.0.cjs
