# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
jobs:
- job: ${{ parameters.name }}

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '^10.15.0'
    displayName: use node 10.15.0

  - task: Npm@1
    inputs:
      command: install
    displayName: npm install

  - task: Npm@1
    inputs:
      command: custom
      customCommand: run build:all
    displayName: npm run build:all

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/drop'
      artifactName: 'drop-${{ parameters.name }}'
    displayName: 'publish drop-${{ parameters.name }}'
    condition: 'always()'
