# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
jobs:
    - job: 'unit_tests_and_lints'

      pool:
          vmImage: 'macOS-10.14'

      steps:
          - template: pipeline/install-node-prerequisites.yaml
            parameters:
                useCache: true

    - job: 'publish_build_drops'
      pool:
          vmImage: 'ubuntu-16.04'
      steps:
          - template: pipeline/install-node-prerequisites.yaml

          - script: yarn build:all
            displayName: build:all

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/drop'
                artifactName: 'drop'
            displayName: publish drop

    - job: 'e2e_mac_web_unified'
      pool:
          vmImage: macOS-10.14
      steps:
          - template: pipeline/install-node-prerequisites.yaml
          - template: pipeline/e2e-test-from-agent.yaml
          - template: pipeline/e2e-test-publish-results.yaml
          - template: pipeline/unified/unified-e2e-test-interactive.yaml
          - template: pipeline/unified/unified-e2e-publish-results.yaml

    - job: 'e2e_linux_unified'
      pool:
          vmImage: ubuntu-16.04
      steps:
          - template: pipeline/install-node-prerequisites.yaml
          - template: pipeline/unified/unified-e2e-test-linux.yaml
          - template: pipeline/unified/unified-e2e-publish-results.yaml

    - job: 'e2e_windows_unified'
      pool:
          vmImage: windows-latest
      steps:
          - template: pipeline/install-node-prerequisites.yaml
          - template: pipeline/unified/unified-e2e-test-interactive.yaml
          - template: pipeline/unified/unified-e2e-publish-results.yaml
