# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
jobs:
    - job: 'unit_tests_and_lints'

      pool:
          vmImage: 'macOS-10.13'

      steps:
          - template: pipeline/prerequisites.yaml

          - script: yarn tslint
            displayName: check lint errors

          - script: yarn format-check
            displayName: check formatting errors

          - script: yarn copyrightheaders
            displayName: check copyrightheaders

          - script: yarn test -- --ci
            displayName: run unit tests

          - task: PublishTestResults@2
            inputs:
                testResultsFiles: $(System.DefaultWorkingDirectory)/test-results/unit/junit.xml
                testRunTitle: accessibility-insights-web
            condition: always()
            displayName: publish test results

          - task: PublishCodeCoverageResults@1
            inputs:
                codeCoverageTool: Cobertura
                summaryFileLocation: $(System.DefaultWorkingDirectory)/test-results/unit/coverage/cobertura-coverage.xml
                failIfCoverageEmpty: true
                # We care most about the summary information; adding the detailed files doesn't give enough extra information
                # to be worth the 1min it adds to the build.
                # Consider re-enabling this once https://github.com/Microsoft/azure-pipelines-tasks/issues/4945 is resolved.
                # reportDirectory: $(System.DefaultWorkingDirectory)/test-results/unit/coverage/lcov-report
            displayName: publish code coverage

          # CI build only
          - task: ComponentGovernanceComponentDetection@0
            displayName: 'Component Detection'
            condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
            inputs:
                verbosity: Normal

    - job: 'e2e_tests_and_publish_drop'

      pool:
          vmImage: 'macOS-10.13'

      steps:
          - template: pipeline/prerequisites.yaml
          - template: pipeline/e2e-test.yaml

          - task: PublishTestResults@2
            inputs:
                testResultsFiles: test-results/e2e/junit-e2e.xml
                testRunTitle: accessibility-insights-web e2e
            condition: always()
            displayName: publish e2e test results

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/test-results/e2e'
                artifactName: 'e2e-failure-screenshots'
            condition: always()
            continueOnError: true
            displayName: publish e2e-failure-screenshots

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/drop'
                artifactName: 'drop'
            displayName: publish drop
