# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
schedules:
    - cron: '0 10 * * 1-5'
      displayName: Weekdays at 10AM UTC (3AM PDT)
      branches:
          include:
              - main
trigger:
    - build-reliability/*
pr:
    paths:
        include:
            - Gruntfile.js
            - targets.config.js
            - tsconfig.json
            - webpack.config.js
            - esbuild.js
            - style-config.js

# The `resources` specify the location and version of the 1ES PT.
resources:
    repositories:
        - repository: 1esPipelines
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release

extends:
    # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
    # For non-production pipelines, use "Unofficial" as defined below.
    # For productions pipelines, use "Official".
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
    parameters:
        # Update the pool with your team's 1ES hosted pool.
        pool:
            name: $(a11yInsightsPool) # Name of your hosted pool
            image: windows-2022-secure # Name of the image in your pool. If not specified, first image of the pool is used
            os: windows
        sdl:
            codeql:
                compiled:
                    enabled: true
                runSourceLanguagesInSourceAnalysis: true
        stages:
            - stage: Stage
              jobs:
                  - template: pipeline/build-all-job-per-environment.yaml@self
                    parameters: { jobNameSuffix: _1 }

                  - template: pipeline/build-all-job-per-environment.yaml@self
                    parameters: { jobNameSuffix: _2 }

                  - template: pipeline/build-all-job-per-environment.yaml@self
                    parameters: { jobNameSuffix: _3 }

                  - template: pipeline/build-all-job-per-environment.yaml@self
                    parameters: { jobNameSuffix: _4 }

                  - template: pipeline/build-all-job-per-environment.yaml@self
                    parameters: { jobNameSuffix: _5 }
