# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
trigger:
    - master
    - e2e-reliability/*
pr:
    paths:
        include:
            - src/tests/end-to-end/

jobs:
    - job: 'e2e_tests_windows_1'
      pool:
          vmImage: 'vs2017-win2016'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_windows_2'
      pool:
          vmImage: 'vs2017-win2016'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_windows_3'
      pool:
          vmImage: 'vs2017-win2016'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_windows_4'
      pool:
          vmImage: 'vs2017-win2016'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_windows_5'
      pool:
          vmImage: 'vs2017-win2016'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_mac_1'
      pool:
          vmImage: 'macOS-10.14'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_mac_2'
      pool:
          vmImage: 'macOS-10.14'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_mac_3'
      pool:
          vmImage: 'macOS-10.14'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_mac_4'
      pool:
          vmImage: 'macOS-10.14'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_mac_5'
      pool:
          vmImage: 'macOS-10.14'
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml


    - job: 'e2e_tests_linux_1'
      pool:
          vmImage: 'ubuntu-16.04'
      steps:
          - template: ./e2e-test-from-docker.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_linux_2'
      pool:
          vmImage: 'ubuntu-16.04'
      steps:
          - template: ./e2e-test-from-docker.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_linux_3'
      pool:
          vmImage: 'ubuntu-16.04'
      steps:
          - template: ./e2e-test-from-docker.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_linux_4'
      pool:
          vmImage: 'ubuntu-16.04'
      steps:
          - template: ./e2e-test-from-docker.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_tests_linux_5'
      pool:
          vmImage: 'ubuntu-16.04'
      steps:
          - template: ./e2e-test-from-docker.yaml
          - template: ./e2e-test-publish-results.yaml
