# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
schedules:
    - cron: '0 8 * * 1-5'
      displayName: Weekdays at 8AM UTC (1AM PDT)
      branches:
          include:
              - main
trigger:
    - e2e-reliability/*
pr:
    paths:
        include:
            - src/tests/end-to-end/
            - Dockerfile

jobs:
    - template: ./e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _1 }

    - template: ./e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _2 }

    - template: ./e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _3 }

    - template: ./e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _4 }

    - template: ./e2e-job-per-environment.yaml
      parameters: { jobNameSuffix: _5 }
