# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
    jobNameSuffix: ''
    windowsImage: 'windows-2019'
    macImage: 'macOS-11'
    linuxImage: 'ubuntu-20.04'

jobs:
    - job: 'e2e_mv3_tests_windows${{ parameters.jobNameSuffix }}'
      pool:
          vmImage: ${{ parameters.windowsImage }}
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-mv3-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_mv3_tests_mac${{ parameters.jobNameSuffix }}'
      pool:
          vmImage: ${{ parameters.macImage }}
      steps:
          - template: ./install-node-prerequisites.yaml
          - template: ./e2e-mv3-test-from-agent.yaml
          - template: ./e2e-test-publish-results.yaml

    - job: 'e2e_mv3_tests_linux${{ parameters.jobNameSuffix }}'
      pool:
          vmImage: ${{ parameters.linuxImage }}
      steps:
          - template: ./run-tests-in-docker-linux.yaml
            parameters:
                target: web-mv3
          - template: ./e2e-test-publish-results.yaml
