# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    unsignedPipelineResource: null
    unsignedArtifactName: null
    signedArtifactName: null

jobs:
    - job: ${{ parameters.signedArtifactName }}
      pool:
          vmImage: 'ubuntu-18.04'
      steps:
          - template: ../../install-node-prerequisites.yaml

          - task: DownloadPipelineArtifact@2
            inputs:
                source: 'specific'
                runVersion: 'specific'
                project: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.projectID)
                pipeline: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.pipelineID)
                runId: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.runID)
                artifact: ${{ parameters.unsignedArtifactName }}
                path: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}'

          - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
            displayName: 'Send to ESRP Code Signing'
            inputs:
                ConnectedServiceName: 'ESRP Code Signing'
                FolderPath: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}'
                Pattern: '*.AppImage'
                signConfigType: inlineSignParams
                inlineOperation: |
                    [
                        {
                            "keyCode": "CP-450779-Pgp",
                            "operationSetCode": "PgpClearSign",
                            "parameters": [],
                            "toolName": "sign",
                            "toolVersion": "1.0"
                        }
                    ]

          - script: node ./pipeline/scripts/update-latest-yml.js signing-in-progress/${{ parameters.signedArtifactName }}/packed linux
            displayName: update electron-builder latest yaml after signing

          - template: ../publish-packed-build-output.yaml
            parameters:
                packedOutputPath: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}/packed'
                artifactName: ${{ parameters.signedArtifactName }}
