# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    vmImage: null
    filePattern: null
    inlineSignParams: null
    unsignedPipelineResource: null
    unsignedArtifactName: null
    signedArtifactName: null

jobs:
    - job: $(signedArtifactName)
      pool:
          vmImage: $(vmImage)
      steps:
          - template: ../install-node-prerequisites.yaml

          - task: DownloadBuildArtifacts@0
            inputs:
                artifactName: $(unsignedArtifactName)
                downloadPath: '$(System.DefaultWorkingDirectory)/signing-in-progress/$(signedArtifactName)'
                buildType: specific
                buildVersionToDownload: specific
                project: $(unsignedPipelineResource.projectID)
                pipeline: $(unsignedPipelineResource.pipelineID)
                buildId: $(unsignedPipelineResource.runID)

          - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
            displayName: 'Send to ESRP Code Signing service'
            inputs:
                ConnectedServiceName: 'ESRP Code Signing'
                FolderPath: '$(System.DefaultWorkingDirectory)/signing-in-progress/$(signedArtifactName)'
                Pattern: $(filePattern)
                signConfigType: inlineSignParams
                inlineOperation: $(inlineSignParams)

          - script: yarn update:electron-checksum
            displayName: update electron checksum after signing

          - template: publish-packed-build-output.yaml
            parameters:
                packedOutputPath: '$(System.DefaultWorkingDirectory)/signing-in-progress/$(signedArtifactName)'
                artifactName: $(signedArtifactName)
