# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    unsignedPipelineResource: null
    unsignedArtifactName: null
    signedArtifactName: null
    channel: null

jobs:
    - template: sign-release-package.yaml
      parameters:
          unsignedPipelineResource: ${{ parameters.unsignedPipelineResource }}
          unsignedArtifactName: ${{ parameters.unsignedArtifactName }}
          signedArtifactName: ${{ parameters.signedArtifactName }}
          channel: ${{ parameters.channel }}
          vmImage: windows-2019
          filePattern: '*.exe, *.dll'
          platform: windows
          inlineSignParams: |
              [
                  {
                  "keyCode": "CP-230012",
                  "operationSetCode": "SigntoolSign",
                  "parameters": [
                      {
                      "parameterName": "OpusName",
                      "parameterValue": "Microsoft"
                      },
                      {
                      "parameterName": "OpusInfo",
                      "parameterValue": "http://www.microsoft.com"
                      },
                      {
                      "parameterName": "PageHash",
                      "parameterValue": "/NPH"
                      },
                      {
                      "parameterName": "FileDigest",
                      "parameterValue": "/fd sha256"
                      },
                      {
                      "parameterName": "TimeStamp",
                      "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                      }
                  ],
                  "toolName": "signtool.exe",
                  "toolVersion": "6.2.9304.0"
                  }
              ]
