# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    # canary | insider | production
    channel: null
    # Should come from a pipeline resource based on build-unsigned-release-packages.yaml
    unsignedPipelineResource: null

jobs:
    - template: sign-release-package-windows.yaml
      parameters:
          unsignedPipelineResource: ${{ parameters.unsignedPipelineResource }}
          unsignedArtifactName: unified-windows-${{ parameters.channel }}-unsigned
          signedArtifactName: unified_windows_${{ parameters.channel }}_signed
          channel: ${{ parameters.channel }}

    - template: sign-release-package-mac.yaml
      parameters:
          unsignedPipelineResource: ${{ parameters.unsignedPipelineResource }}
          unsignedArtifactName: unified-mac-${{ parameters.channel }}-unsigned
          signedArtifactName: unified_mac_${{ parameters.channel }}_signed
          channel: ${{ parameters.channel }}

    - template: sign-release-package-linux.yaml
      parameters:
          unsignedPipelineResource: ${{ parameters.unsignedPipelineResource }}
          unsignedArtifactName: unified-linux-${{ parameters.channel }}-unsigned
          signedArtifactName: unified_linux_${{ parameters.channel }}_signed
