# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    unsignedPipelineResource: null
    unsignedArtifactName: null
    signedArtifactName: null

jobs:
    - job: ${{ parameters.signedArtifactName }}
      pool:
          vmImage: macOS-10.15
      steps:
          - template: ../../install-node-prerequisites.yaml

          - task: DownloadPipelineArtifact@2
            inputs:
                source: 'specific'
                runVersion: 'specific'
                project: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.projectID)
                pipeline: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.pipelineID)
                runId: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.runID)
                artifact: ${{ parameters.unsignedArtifactName }}
                path: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}'

          - task: UseDotNet@2
            displayName: 'Use .NET Core 2.1.0 for ESRP mac mitigation'
            inputs:
                packageType: sdk
                version: 2.1.x
                installationPath: $(Agent.ToolsDirectory)/dotnet

          - template: sign-release-package.yaml
            parameters:
                filePattern: '*.dmg, *.zip'
                platform: mac
                signedArtifactName: ${{ parameters.signedArtifactName }}
                inlineSignParams: |
                    [
                        {
                            "keyCode": "CP-401337-Apple",
                            "operationSetCode": "MacAppDeveloperSign",
                            "parameters": [],
                            "toolName": "sign",
                            "toolVersion": "1.0"
                        }
                    ]
