// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
import { guidanceTags } from 'common/guidance-links';

export const guidanceMetadata = {
    WCAG_1_1_1: { name: 'WCAG 1.1.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html', guidanceTags: [] },
    WCAG_1_2_1: {
        name: 'WCAG 1.2.1',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-only-and-video-only-prerecorded',
        guidanceTags: [],
    },
    WCAG_1_2_2: { name: 'WCAG 1.2.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded.html', guidanceTags: [] },
    WCAG_1_2_3: {
        name: 'WCAG 1.2.3',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-or-media-alternative-prerecorded',
        guidanceTags: [],
    },
    WCAG_1_2_4: { name: 'WCAG 1.2.4', link: 'https://www.w3.org/WAI/WCAG21/Understanding/captions-live.html', guidanceTags: [] },
    WCAG_1_2_5: { name: 'WCAG 1.2.5', link: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-prerecorded', guidanceTags: [] },
    WCAG_1_3_1: { name: 'WCAG 1.3.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships', guidanceTags: [] },
    WCAG_1_3_2: { name: 'WCAG 1.3.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html', guidanceTags: [] },
    WCAG_1_3_3: { name: 'WCAG 1.3.3', link: 'https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics.html', guidanceTags: [] },
    WCAG_1_3_4: {
        name: 'WCAG 1.3.4',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/orientation.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_1_3_5: {
        name: 'WCAG 1.3.5',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_1_4_1: { name: 'WCAG 1.4.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html', guidanceTags: [] },
    WCAG_1_4_2: { name: 'WCAG 1.4.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/audio-control.html', guidanceTags: [] },
    WCAG_1_4_3: { name: 'WCAG 1.4.3', link: 'https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html', guidanceTags: [] },
    WCAG_1_4_4: { name: 'WCAG 1.4.4', link: 'https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html', guidanceTags: [] },
    WCAG_1_4_5: { name: 'WCAG 1.4.5', link: 'https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html', guidanceTags: [] },
    WCAG_1_4_10: {
        name: 'WCAG 1.4.10',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/reflow.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_1_4_11: {
        name: 'WCAG 1.4.11',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_1_4_12: {
        name: 'WCAG 1.4.12',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_1_4_13: {
        name: 'WCAG 1.4.13',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_2_1_1: { name: 'WCAG 2.1.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html', guidanceTags: [] },
    WCAG_2_1_2: { name: 'WCAG 2.1.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/no-keyboard-trap.html', guidanceTags: [] },
    WCAG_2_1_4: {
        name: 'WCAG 2.1.4',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_2_2_1: { name: 'WCAG 2.2.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html', guidanceTags: [] },
    WCAG_2_2_2: { name: 'WCAG 2.2.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide', guidanceTags: [] },
    WCAG_2_3_1: {
        name: 'WCAG 2.3.1',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold.html',
        guidanceTags: [],
    },
    WCAG_2_4_1: { name: 'WCAG 2.4.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks', guidanceTags: [] },
    WCAG_2_4_2: { name: 'WCAG 2.4.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html', guidanceTags: [] },
    WCAG_2_4_3: { name: 'WCAG 2.4.3', link: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html', guidanceTags: [] },
    WCAG_2_4_4: { name: 'WCAG 2.4.4', link: 'https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html', guidanceTags: [] },
    WCAG_2_4_5: { name: 'WCAG 2.4.5', link: 'https://www.w3.org/WAI/WCAG21/Understanding/multiple-ways.html', guidanceTags: [] },
    WCAG_2_4_6: { name: 'WCAG 2.4.6', link: 'https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels', guidanceTags: [] },
    WCAG_2_4_7: { name: 'WCAG 2.4.7', link: 'https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html', guidanceTags: [] },
    WCAG_2_5_1: {
        name: 'WCAG 2.5.1',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_2_5_2: {
        name: 'WCAG 2.5.2',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_2_5_3: {
        name: 'WCAG 2.5.3',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/label-in-name',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_2_5_4: {
        name: 'WCAG 2.5.4',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
    WCAG_2_5_5: { name: 'WCAG 2.5.5', link: 'https://www.w3.org/WAI/WCAG21/Understanding/target-size.html', guidanceTags: [] },
    WCAG_3_1_1: { name: 'WCAG 3.1.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/language-of-page.html', guidanceTags: [] },
    WCAG_3_1_2: { name: 'WCAG 3.1.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html', guidanceTags: [] },
    WCAG_3_2_1: { name: 'WCAG 3.2.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/on-focus.html', guidanceTags: [] },
    WCAG_3_2_2: { name: 'WCAG 3.2.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/on-input.html', guidanceTags: [] },
    WCAG_3_2_3: { name: 'WCAG 3.2.3', link: 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation', guidanceTags: [] },
    WCAG_3_2_4: { name: 'WCAG 3.2.4', link: 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification', guidanceTags: [] },
    WCAG_3_3_1: { name: 'WCAG 3.3.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/error-identification.html', guidanceTags: [] },
    WCAG_3_3_2: { name: 'WCAG 3.3.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html', guidanceTags: [] },
    WCAG_3_3_3: { name: 'WCAG 3.3.3', link: 'https://www.w3.org/WAI/WCAG21/Understanding/error-suggestion.html', guidanceTags: [] },
    WCAG_3_3_4: {
        name: 'WCAG 3.3.4',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-legal-financial-data.html',
        guidanceTags: [],
    },
    WCAG_4_1_1: { name: 'WCAG 4.1.1', link: 'https://www.w3.org/WAI/WCAG21/Understanding/parsing.html', guidanceTags: [] },
    WCAG_4_1_2: { name: 'WCAG 4.1.2', link: 'https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html', guidanceTags: [] },
    WCAG_4_1_3: {
        name: 'WCAG 4.1.3',
        link: 'https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html',
        guidanceTags: [guidanceTags.WCAG_2_1],
    },
};
