// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
import { GuidanceTag } from 'content/guidance-tags';
import { link } from 'content/link';
import { HyperlinkDefinition } from 'views/content/content-page';
import { DictionaryStringTo } from '../types/common-types';

export interface GuidanceLink {
    href: string;
    text: string;
    tags?: GuidanceTag[];
}

const BestPractice: HyperlinkDefinition = {
    text: 'Best Practice',
    href: '',
};

export const ruleToLinkConfiguration: DictionaryStringTo<HyperlinkDefinition[]> = {
    accesskeys: [link.WCAG_2_1_1],
    blink: [link.WCAG_2_2_2],
    bypass: [link.WCAG_2_4_1],
    checkboxgroup: [BestPractice],
    dlitem: [link.WCAG_1_3_1],
    label: [link.WCAG_1_3_1, link.WCAG_3_3_2],
    list: [link.WCAG_1_3_1],
    listitem: [link.WCAG_1_3_1],
    marquee: [link.WCAG_2_2_2],
    radiogroup: [BestPractice],
    region: [BestPractice],
    tabindex: [BestPractice],
    'area-alt': [link.WCAG_1_1_1],
    'aria-allowed-attr': [link.WCAG_4_1_1, link.WCAG_4_1_2],
    'aria-allowed-role': [BestPractice],
    'aria-dpub-role-fallback': [BestPractice],
    'aria-hidden-body': [link.WCAG_4_1_2],
    'aria-hidden-focus': [link.WCAG_4_1_2, link.WCAG_1_3_1],
    'aria-input-field-name': [link.WCAG_4_1_2],
    'aria-required-attr': [link.WCAG_4_1_1, link.WCAG_4_1_2],
    'aria-required-children': [link.WCAG_1_3_1],
    'aria-required-parent': [link.WCAG_1_3_1],
    'aria-roles': [link.WCAG_1_3_1, link.WCAG_4_1_1, link.WCAG_4_1_2],
    'aria-toggle-field-name': [link.WCAG_4_1_2],
    'aria-valid-attr': [link.WCAG_4_1_1],
    'aria-valid-attr-value': [link.WCAG_4_1_1, link.WCAG_4_1_2],
    'audio-caption': [link.WCAG_1_2_1],
    'autocomplete-valid': [link.WCAG_1_3_5],
    'avoid-inline-spacing': [link.WCAG_1_4_12],
    'button-name': [link.WCAG_4_1_2],
    'color-contrast': [link.WCAG_1_4_3],
    'css-orientation-lock': [BestPractice],
    'definition-list': [link.WCAG_1_3_1],
    'document-title': [link.WCAG_2_4_2],
    'duplicate-id': [link.WCAG_4_1_1],
    'duplicate-id-active': [link.WCAG_4_1_1],
    'duplicate-id-aria': [link.WCAG_4_1_1],
    'empty-heading': [BestPractice],
    'focus-order-semantics': [BestPractice],
    'form-field-multiple-labels': [BestPractice],
    'frame-tested': [BestPractice],
    'frame-title': [link.WCAG_2_4_1],
    'frame-title-unique': [BestPractice],
    'get-frame-title': [link.WCAG_4_1_2],
    'heading-order': [BestPractice],
    'hidden-content': [BestPractice],
    'href-no-hash': [BestPractice],
    'html-has-lang': [link.WCAG_3_1_1],
    'html-lang-valid': [link.WCAG_3_1_1],
    'html-xml-lang-mismatch': [link.WCAG_3_1_1],
    'image-alt': [link.WCAG_1_1_1],
    'image-redundant-alt': [BestPractice],
    'input-button-name': [link.WCAG_4_1_2],
    'input-image-alt': [link.WCAG_1_1_1],
    'label-content-name-mismatch': [BestPractice],
    'label-title-only': [BestPractice],
    'landmark-banner-is-top-level': [link.WCAG_1_3_1, BestPractice],
    'landmark-complementary-is-top-level': [link.WCAG_1_3_1, BestPractice],
    'landmark-contentinfo-is-top-level': [link.WCAG_1_3_1, BestPractice],
    'landmark-main-is-top-level': [link.WCAG_1_3_1, BestPractice],
    'landmark-no-duplicate-banner': [link.WCAG_1_3_1, BestPractice],
    'landmark-no-duplicate-contentinfo': [link.WCAG_1_3_1, BestPractice],
    'landmark-one-main': [BestPractice],
    'landmark-unique': [BestPractice],
    'layout-table': [link.WCAG_1_3_1],
    'link-in-text-block': [BestPractice],
    'link-name': [link.WCAG_2_4_4, link.WCAG_4_1_2],
    'meta-refresh': [link.WCAG_2_2_1],
    'meta-viewport': [link.WCAG_1_4_4],
    'meta-viewport-large': [BestPractice],
    'object-alt': [link.WCAG_1_1_1],
    'p-as-heading': [BestPractice],
    'page-has-heading-one': [BestPractice],
    'page-title': [link.WCAG_2_4_2],
    'role-img-alt': [link.WCAG_1_1_1],
    'scope-attr-valid': [BestPractice],
    'scrollable-region-focusable': [link.WCAG_2_1_1, BestPractice],
    'server-side-image-map': [link.WCAG_2_1_1],
    'skip-link': [BestPractice],
    'table-duplicate-name': [BestPractice],
    'table-fake-caption': [BestPractice],
    'td-has-header': [BestPractice],
    'td-headers-attr': [link.WCAG_1_3_1],
    'th-has-data-cells': [link.WCAG_1_3_1],
    'unique-landmark': [link.WCAG_2_4_1, BestPractice],
    'valid-lang': [link.WCAG_3_1_2],
    'video-caption': [link.WCAG_1_2_2],
    'video-description': [link.WCAG_1_2_5],
};
