# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Note: this will become the version of the released packages!
# must be parseable by node-semver, so month leading zero is omitted
name: $(Year:yyyy).$(Date:Mdd).$(Rev:r)

trigger: none

strategy:
    matrix:
        windows: { vmImage: 'windows-latest', platform: 'windows' }
        mac: { vmImage: 'macOS-10.15', platform: 'mac' }
        linux: { vmImage: 'ubuntu-18.04', platform: 'linux' }

pool:
    vmImage: $(vmImage)

variables:
    RUN_RELEASE_TESTS: true

steps:
    - template: ../install-node-prerequisites.yaml

    - template: ./download-electron-mirror.yaml

    - task: ComponentGovernanceComponentDetection@0
      displayName: 'dependency detection (Component Governance)'
      inputs:
          detectorsFilter: Yarn
          ignoreDirectories: 'drop,dist,extension,node_modules'
          verbosity: Normal
      timeoutInMinutes: 5

    - task: msospo.ospo-extension.8d7f9abb-6896-461d-9e25-4f74ed65ddb2.notice@0
      displayName: 'generate NOTICE.html file'
      inputs:
          outputfile: '$(System.DefaultWorkingDirectory)/src/NOTICE.html'
          outputformat: html
      timeoutInMinutes: 5

    - template: ./unified-e2e-test-interactive.yaml
    - template: ./unified-e2e-publish-results.yaml

    - script: yarn build:unified:all --unified-version=$(Build.BuildNumber) --unified-canary-instrumentation-key=$(UnifiedCanaryInstrumentationKey) --unified-insider-instrumentation-key=$(UnifiedInsiderInstrumentationKey) --unified-prod-instrumentation-key=$(UnifiedProdInstrumentationKey)
      displayName: yarn build:unified:all

    - script: yarn pack:unified:all
      displayName: yarn pack:unified:all
      condition: and(succeeded(), ne(variables.platform, 'windows'))

    - script: node ./pipeline/scripts/print-file-hash-info.js $(System.DefaultWorkingDirectory)/drop/electron/unified-canary/packed
      displayName: print out canary file hashes

    - template: ./binskim-analysis.yaml

    - template: publish-build-output.yaml
      parameters:
          buildOutputPath: '$(System.DefaultWorkingDirectory)/drop/electron/unified-canary'
          artifactName: unified-$(platform)-canary-unsigned

    - template: publish-build-output.yaml
      parameters:
          buildOutputPath: '$(System.DefaultWorkingDirectory)/drop/electron/unified-insider'
          artifactName: unified-$(platform)-insider-unsigned

    - template: publish-build-output.yaml
      parameters:
          buildOutputPath: '$(System.DefaultWorkingDirectory)/drop/electron/unified-production'
          artifactName: unified-$(platform)-production-unsigned
