# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: InsiderProductionSigning-$(Rev:r)

trigger: none

resources:
    pipelines:
        - pipeline: build-unsigned-release-packages
          source: Accessibility Insights Unified - build-unsigned-release-packages
          trigger: none # manual

jobs:
    - template: channel/sign-release-packages-for-channel.yaml
      parameters:
          unsignedPipelineResource: build-unsigned-release-packages
          channel: insider

    - template: channel/sign-release-packages-for-channel.yaml
      parameters:
          unsignedPipelineResource: build-unsigned-release-packages
          channel: production
