# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
jobs:
    - job: 'build_product_windows'

      pool:
          vmImage: 'windows-latest'

      steps:
          - script: 'rmdir /s /q %LOCALAPPDATA%\electron\Cache'
            displayName: 'delete electron binary from cache'
            continueOnError: true

          - template: ../install-node-prerequisites.yaml
          - template: electron-e2e-test-interactive.yaml
          - template: electron-e2e-publish-results.yaml

          - template: distribute-sign-publish-electron-windows.yaml

    - job: 'build_product_linux'

      pool:
          vmImage: 'ubuntu-16.04'

      steps:
          - script: 'sudo rm -rf ~/.cache/electron/'
            displayName: 'delete electron binary from cache'
            continueOnError: true

          - template: ../install-node-prerequisites.yaml
          - template: electron-e2e-test-linux.yaml
          - template: electron-e2e-publish-results.yaml

          - template: distribute-electron-linux.yaml

    - job: 'build_product_mac'
      pool:
          vmImage: macOS-10.14
      steps:
          - script: 'rm -rf ~/Library/Caches/electron/'
            displayName: 'delete electron binary from cache'
            continueOnError: true

          - template: ../install-node-prerequisites.yaml
          - template: electron-e2e-test-interactive.yaml
          - template: electron-e2e-publish-results.yaml

          - template: distribute-sign-publish-electron-mac.yaml
