// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
export enum VisualizationType {
    Headings,
    Issues,
    Landmarks,
    TabStops,
    Color,
    NeedsReview,
    HeadingsAssessment,
    ColorSensoryAssessment,
    LanguageAssessment,
    LandmarksAssessment,
    PageAssessment,
    RepetitiveContentAssessment,
    KeyboardInteraction,
    AudioVideOnly,
    ErrorsAssessment,
    TimedEventsAssessment,
    ParsingAssessment,
    PrerecordedMultimediaAssessment,
    LiveMultimediaAssessment,
    VisibleFocusOrderAssessment,
    ImagesAssessment,
    TextLegibility,
    LinksAssessment,
    NativeWidgets,
    CustomWidgets,
    AutomatedChecks,
    SequenceAssessment,
    SemanticsAssessment,
    PointerMotionAssessment,
    ContrastAssessment,
}
